In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp
import random
import re
import textwrap
import string
import warnings
warnings.filterwarnings('ignore')
import csv
import seaborn as sbn
%matplotlib inline
from sklearn import linear_model
import math
pd.options.display.float_format = '{:.3f}'.format

In [70]:
crime = pd.read_csv('table_8_offenses_known_to_law_enforcement_new_york_by_city_2013_clean.csv')

In [71]:
crime.shape

(351, 14)

In [72]:
columns = ['City', 'Population', 'Violent_Crimes', 'Murder_Manslaughter', 'Rape_revdef', 'Rape_olddef', 'Robbery', 'Aggravated_Assault', 'Property_Crime', 
              'Burglary', 'Larceny_Theft', 'Motor_Vehicle_Theft', 'Arson', 'Unnamed']

In [73]:
crime.columns=columns
crime[columns]=crime[columns].replace(',', '', regex=True)
crime.drop(crime.head(4).index, inplace=True)
crime_new=crime.drop(['Rape_revdef', 'Unnamed'], axis=1)
crime_new.head()

,City,Population,Violent_Crimes,Murder_Manslaughter,Rape_olddef,Robbery,Aggravated_Assault,Property_Crime,Burglary,Larceny_Theft,Motor_Vehicle_Theft,Arson
4,Albion Village,6388,23,0.000,3,4,16,223,53,165,5,nan
5,Alfred Village,4089,5,0.000,0,3,2,46,10,36,0,nan
6,Allegany Village,1781,3,0.000,0,0,3,10,0,10,0,0.000
7,Amherst Town,118296,107,1.000,7,31,68,2118,204,1882,32,3.000
8,Amityville Village,9519,9,0.000,2,4,3,210,16,188,6,1.000

In [74]:
crime_new.dropna()

,City,Population,Violent_Crimes,Murder_Manslaughter,Rape_olddef,Robbery,Aggravated_Assault,Property_Crime,Burglary,Larceny_Theft,Motor_Vehicle_Theft,Arson
6,Allegany Village,1781,3,0.000,0,0,3,10,0,10,0,0.000
7,Amherst Town,118296,107,1.000,7,31,68,2118,204,1882,32,3.000
8,Amityville Village,9519,9,0.000,2,4,3,210,16,188,6,1.000
9,Amsterdam,18182,30,0.000,0,12,18,405,99,291,15,0.000
10,Arcade Village,2053,0,0.000,0,0,0,39,3,35,1,0.000
11,Ardsley Village,4523,5,0.000,0,3,2,33,4,28,1,0.000
12,Asharoken Village,658,0,0.000,0,0,0,2,0,2,0,0.000
13,Attica Village,2522,2,0.000,0,0,2,5,0,4,1,0.000
16,Baldwinsville Village,7473,5,0.000,0,1,4,88,10,77,1,0.000
17,Ballston Spa Village,5418,8,0.000,0,3,5,94,16,78,0,1.000
19,Bath Village,5733,15,0.000,1,3,11,191,32,157,2,2.000
23,Black River,1410,0,0.000,0,0,0,14,2,12,0,0.000
25,Bolivar Village,1022,1,0.000,0,0,1,4,2,2,0,0.000
26,Bolton Town,2325,2,0.000,0,0,2,24,4,20,0,0.000
27,Boonville Village,2054,1,0.000,0,0,1,20,6,14,0,0.000
28,Brant Town,2065,4,0.000,0,1,3,31,9,20,2,0.000
29,Brewster,2358,0,0.000,0,0,0,13,3,10,0,0.000
30,Briarcliff Manor Village,7976,1,0.000,0,0,1,11,1,10,0,0.000
33,Bronxville Village,6390,0,0.000,0,0,0,47,5,39,3,0.000
34,Brownville Village,1174,0,0.000,0,0,0,10,0,10,0,0.000
38,Camden Village,2219,5,0.000,0,0,5,46,4,42,0,0.000
39,Camillus Town and Village,24165,14,0.000,1,0,13,348,36,307,5,1.000
42,Canisteo Village,2246,3,0.000,0,1,2,12,3,9,0,0.000
44,Cape Vincent Village,762,0,0.000,0,0,0,2,0,2,0,0.000
45,Carmel Town,34462,10,0.000,2,0,8,198,31,158,9,1.000
46,Carroll Town,3481,0,0.000,0,0,0,8,3,5,0,0.000
48,Cattaraugus Village,980,0,0.000,0,0,0,4,0,4,0,0.000
51,Central Square Village,1835,3,0.000,0,2,1,53,6,45,2,0.000
52,Chatham Village,1733,3,0.000,0,0,3,32,5,27,0,0.000
53,Cheektowaga Town,78361,158,0.000,11,48,99,2689,345,2271,73,2.000
...,...,...,...,...,...,...,...,...,...,...,...,...
283,Saugerties Town,19318,15,0.000,3,5,7,319,51,268,0,0.000
287,Schoharie Village,872,0,0.000,0,0,0,0,0,0,0,0.000
292,Shelter Island Town,2412,3,0.000,0,0,3,41,2,39,0,0.000
293,Sherburne Village,1351,1,0.000,0,0,1,15,7,8,0,0.000
295,Shortsville Village,1437,0,0.000,0,0,0,0,0,0,0,0.000
297,Skaneateles Village,2450,0,0.000,0,0,0,10,2,8,0,0.000
298,Sleepy Hollow Village,9996,8,1.000,0,1,6,58,9,47,2,0.000
300,Solvay Village,6487,19,0.000,0,6,13,186,38,142,6,0.000
301,Southampton Town,50603,44,0.000,6,16,22,1020,219,752,49,1.000
306,Stillwater Town,6587,1,0.000,0,0,1,24,4,18,2,1.000
309,Suffern Village,10886,9,0.000,0,1,8,60,11,48,1,0.000
310,Syracuse,143834,1192,21.000,75,400,696,6473,1781,4298,394,57.000
311,Tarrytown Village,11449,6,0.000,0,3,3,110,12,94,4,0.000
313,Tonawanda,14987,34,0.000,0,4,30,315,24,289,2,4.000
314,Tonawanda Town,58082,118,1.000,5,26,86,1099,190,882,27,1.000
315,Troy,49898,371,1.000,14,145,211,1985,593,1305,87,5.000
317,Tuckahoe Village,6578,0,0.000,0,0,0,35,7,27,1,0.000
319,Tuxedo Park Village,615,0,0.000,0,0,0,0,0,0,0,0.000
324,Wallkill Town,27940,40,0.000,3,16,21,767,91,650,26,1.000
326,Warsaw Village,3453,6,0.000,1,0,5,78,5,73,0,0.000
327,Washingtonville Village,5828,2,0.000,0,1,1,58,5,51,2,0.000
328,Waterford Town and Village,8392,4,0.000,0,0,4,59,6,52,1,0.000
335,Weedsport Village,1797,0,0.000,0,0,0,25,5,20,0,0.000
336,Wellsville Village,4574,11,0.000,1,0,10,164,32,129,3,1.000
337,Westhampton Beach Village,1732,2,0.000,0,0,2,44,4,37,3,0.000
338,West Seneca Town,44821,35,1.000,1,9,24,896,166,710,20,0.000
341,Whitesboro Village,3733,4,0.000,0,0,4,36,14,21,1,0.000
342,Whitestown Town,9141,0,0.000,0,0,0,77,13,61,3,0.000
344,Woodridge Village,829,7,0.000,0,0,7,17,8,9,0,0.000
346,Yonkers,199134,1036,6.000,25,390,615,2368,470,1662,236,10.000

In [75]:
crime_new['PopSq']=crime_new['Population'].apply(float)**2
crime_new['Murder_new']=np.where(crime_new['Murder_Manslaughter'] > 0, 1, 0)
crime_new['Robbery_new']=np.where(crime_new['Robbery'].apply(float) > 0, 1, 0)
crime_new.head()

,City,Population,Violent_Crimes,Murder_Manslaughter,Rape_olddef,Robbery,Aggravated_Assault,Property_Crime,Burglary,Larceny_Theft,Motor_Vehicle_Theft,Arson,PopSq,Murder_new,Robbery_new
4,Albion Village,6388,23,0.000,3,4,16,223,53,165,5,nan,40806544.000,0,1
5,Alfred Village,4089,5,0.000,0,3,2,46,10,36,0,nan,16719921.000,0,1
6,Allegany Village,1781,3,0.000,0,0,3,10,0,10,0,0.000,3171961.000,0,0
7,Amherst Town,118296,107,1.000,7,31,68,2118,204,1882,32,3.000,13993943616.000,1,1
8,Amityville Village,9519,9,0.000,2,4,3,210,16,188,6,1.000,90611361.000,0,1

In [76]:
crime_new1=crime_new[['City','Population','PopSq','Murder_new','Robbery_new']].copy()
crime_new1.head()

                 City Population           PopSq  Murder_new  Robbery_new
4      Albion Village       6388    40806544.000           0            1
5      Alfred Village       4089    16719921.000           0            1
6    Allegany Village       1781     3171961.000           0            0
7        Amherst Town     118296 13993943616.000           1            1
8  Amityville Village       9519    90611361.000           0            1

In [77]:
crime_new1.dtypes

City            object
Population      object
PopSq          float64
Murder_new       int64
Robbery_new      int64
dtype: object